### ISSUE TITLE
コントリビューションについて

### ISSUE THREAD

**Issue by taksas** [mimimimineko/Kadai-Portal#1]
こちらのリポジトリは[Kadai-Portal](https://kadai-portal.mimimimineko.com/)のソースコードをmimimiminekoさんが個人的にホスティングしている（kadai-Portalを配布しているSETOKU公式ではない）と解釈していますが、Kadai-Portalへ何らかのコントリビューションをしたいとき、こちらのリポジトリに直接プルリクを送れば良いのでしょうか。
或いは、こちらのリポジトリはプロダクション環境とは分離された参照用のリポジトリであり、開発はSETOKUメンバーのみで行っていたりするでしょうか。

おれのかんがえた さいきょーのついかきのう を作りだしたので、是非コードレビュー後マージしていただきたいのですが。

**Comment by mimimimineko** [comment]
一応、参照用のリポジトリですが、プルリク送っていただいても問題はありません。  
ただ、レビューが実施されるか、マージされるか、ChromeWebStoreに反映するかはmimimiminekoの対応と”たくさす のかんがえた さいきょーのついかきのう”の便利さオモロさ 安全性次第です。

**Comment by mimimimineko** [comment]
本プロダクションは、mimimimineko🔰が1.5年前に製作開始したものであり、
とうの昔に開発者はフロント無理ンゴーと喚きながら失踪しました。
中身も汚く、恥かしいです。まじまじ見ないでほしい。
アップデートは2022年初夏で停止しており、なけなしの新Moodle対応化が2023春に行われたきりです。

その点ご留意を。

**Comment by mimimimineko** [comment]
あ、あと事後報告ですが、taksas.techにあった GASによる大学サイト監視に インスパイヤを受けた機能が1つ 本プロダクションにありますが、許してニャン
