### ISSUE TITLE
三井住友銀行（direct3.smbc.co.jp）にアクセス時にフィッシング検知機能で誤検知が発生する

### ISSUE THREAD

**Issue by taksas** [mimimimineko/Kadai-Portal#4]
三井住友銀行でログイン暗証を入れずにログインしようとするとdirect.smbc.co.jpからdirect3.smbc.co.jpにリダイレクトされてログインに失敗するのですが、この時Kadai-Portalのフィッシング検知機能が誤検知を起こします。
![SMBCダイレクトログイン ： SMBCダイレクト - Google Chrome 2023_11_06 9_16_12](https://github.com/mimimimineko/Kadai-Portal/assets/63092685/b026f7bc-f9da-4ecc-8929-3c5a3161cee0)

**Comment by mimimimineko** [comment]
ドメインの正規表現の処理の不具合ですね。
後方一致で対応するように変更します。

**Comment by mimimimineko** [comment]
対応完了しました。お手元の端末に反映されるまでしばらくお待ちください。
