### ISSUE TITLE
フィッシング検知発生時のAlert内容

### ISSUE THREAD

**Issue by taksas** [mimimimineko/Kadai-Portal#5]
フィッシング検知機能が反応したときはAlertが出るようになっていますが、タイトルが「<訪れているサイトURL>の内容」になります。

このタイトル自体は変更出来ませんが、訪れているサイト自体がAlertを出しているように見えてしまうので、Alertの内容をより分かりやすくした方が良いように感じます。

## 問題と思う点
「scanned by SETOKU」という表記だけでは何がAlertを出しているのか分からず、表記として不適切

## 改善策
- 何がAlertを出しているのか明確にする
- 訪れているサイト自体が出しているAlertではないことを明確にする
- このAlertについて、問い合わせ先を明確にする

## 改善案
```
フィッシングサイトの恐れがあります。リンク元を確認し、ブックマーク等から再アクセスすることを推奨します。
このアラートはインストールされた拡張機能「Kadai-Portal」から出されました。このアラートについての問い合わせは、訪れているサイトの運営元ではなく香川大学SETOKUまでお願いします。
```

![SMBCダイレクトログイン ： SMBCダイレクト - Google Chrome 2023_11_06 9_16_12](https://github.com/mimimimineko/Kadai-Portal/assets/63092685/ebc1975b-b002-4800-91f7-6f2718c41da9)

**Comment by mimimimineko** [comment]
@taksas 氏におかれましては、普段から本拡張機能をご利用いただきありがとうございます。

本拡張機能の開発は2022年度のSETOKUの新歓宣伝で使うというのをモチベに始めたのですが、役割を終え、個人開発物としての色が強くなってます。ですのでscanned by SETOKUの表現は変更したほうが良いと感じておりました。是非、taksas氏の案を採用したいと思います。

機能のオンオフができないことも問題であると感じておりますが、 @mimimimineko が逃亡しかけており、進んでおりません。
良いものは、基本的に取り入れ、マージしていく方針なので、是非プルリクお待ちしております。

**Comment by mimimimineko** [comment]
![image](https://github.com/mimimimineko/Kadai-Portal/assets/80242131/8d82a6b7-5d4c-408d-ae4a-28e3596a2199)
文面を変更しました。お手元の端末へ反映されるまで数日お待ちください。

**Comment by taksas** [comment]
光の速さでの対応ありがとうございます。

**Comment by mimimimineko** [comment]
Windowsだと、バックスラッシュが￥になっちゃう。
確認不足でしたが、機能自体に影響は無いため、放置します。
(画像は、安全なサイトと思われます)

<img width="328" alt="image" src="https://github.com/mimimimineko/Kadai-Portal/assets/80242131/f4ebe2cf-c990-4138-aac5-3d6b4a08a774">
