### ISSUE TITLE
三井住友カード会員向けサービス「Vpass」（https://www.smbc-card.com/）へのアクセス時、毎回フィッシング検知機能の誤検知が発生する

### ISSUE THREAD

**Issue by taksas** [mimimimineko/Kadai-Portal#7]
https://www.smbc-card.com/mem/index.jsp
上記サイトアクセス時、毎回「タイトルとドメインの組み合わせが不正」というアラートが出ます。
![三井住友カード会員向けサービス「Vpass」ログイン - Google Chrome 2023_11_11 22_44_13](https://github.com/mimimimineko/Kadai-Portal/assets/63092685/f2be0e40-b5c1-4a4c-9262-d45e96e665fa)

**Comment by mimimimineko** [comment]
いつもありがとうございます。
先日変更したフィッシング検知コードのミスです。
修正版をGoogleに投げたので更新までお待ちください。

amazon.com.example.comのような偽サイトがあった場合に、フィッシング偽陰性となってしまうことも確認できましたので、ついでに修正しました。確認の徹底し再発防止に努めます。
