### ISSUE TITLE
フィッシング検知機能における特定ドメインの一括ブロック仕様について

### ISSUE THREAD

**Issue by taksas** [mimimimineko/Kadai-Portal#8]
Kadai-Portalでは特定ドメインのURLについて、一括でブロックされる仕様になっているかと思います。

```
let blacklistDomain = [
    "duckdns.org",
    "cn",
    "ru",
    "is",
    "top",
    "xyz"
]
```

https://github.com/mimimimineko/Kadai-Portal/blob/1cd198f208062b544ae107bc225626dfebe976b7/src/scripts/allsites/scanphishing.js#L28

![【Audacity】音楽ファイルをモノラル↔ステレオに変換する方法 - Google Chrome 2023_11_18 19_13_26](https://github.com/mimimimineko/Kadai-Portal/assets/63092685/f3603c03-bfea-4292-a1e7-d83332e2f036)

xyzドメインがフィッシングサイトにおいて使用率が高く、他のドメインと比べて健全な用途での利用の割合が低いと言われているのは一般的かと思います。

しかしながら、Kadai-Portalがフィッシングサイトの厳格なブロックを目的とした拡張機能ではなく（公式サイトには「香大生応援 Chrome拡張機能」とあります）、フィッシング検知機能があくまでおまけ機能であるとするならば、（xyzドメイン以外も含め）ドメインの一括ブロックはやりすぎであると感じました。

つまるところ、「香川大学関連の機能が入っているらしい拡張機能を入れたら、xyzドメイン（など）を持つすべてのサイトで『フィッシングの恐れあり』というアラートが出る」という現状の実装は過剰な対応ではないか、ということです。

こちらのissueについては提案となります。（当然と言えば当然ですが）mimimiminekoさんがこの仕様が適切であると判断した場合はクローズしていただいて構いません。

**Comment by mimimimineko** [comment]
そもそも、機能のオンオフとか、ブロックしないドメインとか、自分で指定できるようにすればよいのですが、、、
いずれ付けます。この機能が付きましたら、Twitterにてお知らせします。

xyzドメインが一般的に不健全とされる用途で使用されている割合は非常に低いため、ChromrWebStoreから入手できるバージョンへの対応は実施しません。

@taksas 氏の環境への対応はご自身でお願いします。
ブラックリストはソースコード内にハードコートしておりますので、以下の手順で可能です。

1. 本拡張機能をGitHubよりダウンロード
1. 該当箇所を削除またはmanifest.jsonのフィッシング検知のjsの部分を削除
2. chrome://extensionsより手動インストール
